services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo_secure_pass
    volumes:
      - odoo-db:/var/lib/postgresql/data
    restart: always

  odoo:
    image: odoo:17
    depends_on: [db]
    ports: ['8069:8069']
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo_secure_pass
    volumes:
      - odoo-data:/var/lib/odoo
    restart: always

volumes:
  odoo-db:
  odoo-data:
